apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "explorer.fullname" . }}-crypto3
  labels:
    app: {{ template "explorer.name" . }}
    chart: {{ template "explorer.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  {{- (.Files.Glob "crypto-config/peerOrganizations/atlantis.com/users/Admin@atlantis.com/msp/keystore/e12341eb0882a7295c638a60cc627518051e48932e3ff20a7059950540f1e1ac_sk").AsConfig | nindent 2 }}
