apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "explorer.fullname" . }}-crypto1
  labels:
    app: {{ template "explorer.name" . }}
    chart: {{ template "explorer.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  {{- (.Files.Glob "crypto-config/peerOrganizations/aptalkarga.tr/users/Admin@aptalkarga.tr/msp/keystore/ed585db59f69fda7b6b1576cfcb9676b01d54b42805616265f4f4eeb41b685a6_sk").AsConfig | nindent 2 }}
